name: publish-docker

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build image
              run: docker build -t registry.sels-driesen.be/wannes/klecks-chat:latest .

            - name: Push image
              run: docker push registry.sels-driesen.be/wannes/klecks-chat:latest
